[[permission]]
identifier = "shell-commands"
description = "Shell container invoke commands"
commands.allow = [
  "shell_save_file",
  "shell_read_file",
  "shell_delete_file",
  "shell_rename_file",
  "shell_open_file",
  "shell_open_file_location",
  "shell_log",
  "shell_notify",
  "shell_fetch",
  "shell_get_window_position",
  "shell_set_window_position",
  "shell_get_window_size",
  "shell_set_window_size",
  "shell_minimize_window",
  "shell_get_screens",
  "shell_get_screen_at",
  "shell_db_query",
  "shell_db_execute",
  "shell_toggle_devtools",
  "shell_open_window",
  "shell_close_window",
]